import type { TpData } from "./types";

export const rpgTpData: TpData = {
  org: [
    { name: "Wingo", roles: "Host" },
    { name: "Beu", roles: "Admin / Dev" },
    { name: "Neppo", roles: "Admin / Monteur" },
    { name: "PyDelta", roles: "Admin / Testeur" },
    {
      name: "Raikuz",
      roles: "Admin / Testeur / Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3a+Raikuz",
    },
    {
      name: "ziyx_",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3A+ziyx",
    },
    {
      name: "Qiraj",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3a+Qiraj",
    },
    {
      name: "Heasto",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3A+Heasto",
    },
    {
      name: "Onyx_be01",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3A+Onyx_be01",
    },
    {
      name: "SirTalyon",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3A+SirTalyon",
    },
    {
      name: "NeoriionTM",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3A+NeoriionTM",
    },
    {
      name: "Kann",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3a+Kann",
    },
    {
      name: "Wazix.",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3a+Wazix.",
    },
    {
      name: "Roquete.wp",
      roles: "Mappeur",
      exchange: "https://trackmania.exchange/mapsearch?query=author%3a+Roquete.wp",
    },
  ],
  teams: [
    { id: "FCF", name: "FC Fleurs", color: "pink", emoji: "🌺" },
    { id: "GBG", name: "Giga Beaux Gosses", color: "yellow", emoji: "😎" },
    { id: "SOINC", name: "Soinc", color: "blue", emoji: "🦔" },
    { id: "MDR", name: "Mandatory", color: "red", emoji: "🔨" },
    { id: "WQZ", name: "Wauquiez", color: "emerald", emoji: "👴" },
    { id: "PP", name: "Les Pipes", color: "fuchsia", emoji: "🚬" },
    { id: "DOMO", name: "Domo", color: "rose", emoji: "🇯🇵" },
    { id: "HEL", name: "Domo", color: "rose", emoji: "🦴" },
    { id: "SPF", name: "SPF 50", color: "rose", emoji: "☀️" },
    { id: "ACT", name: "Actually", color: "rose", emoji: "🤓" },
    { id: "TT", name: "Turbo Trinité", color: "orange", emoji: "🤓" },
    { id: "PDG", name: "Luck Fursaff", color: "blue", emoji: "🤓" },
    { id: "K2", name: "K2", color: "grey", emoji: "🤓" },
    { id: "GG", name: "GG", color: "blue", emoji: "🤓" },
    { id: "PAC", name: "Paclair", color: "yellow", emoji: "🤓" },
    { id: "CL", name: "Croquette League", color: "blue", emoji: "🤓" },
    { id: "EDW", name: "Edelweiss", color: "white", emoji: "🤓" },
    { id: "STNK", name: "Stonks Industries", color: "green", emoji: "🤓" },
    { id: "P4", name: "Puissance 4", color: "blue", emoji: "🤓" },
    { id: "CUBE", name: "CUBE", color: "brown", emoji: "🤓" },
    { id: "JBL", name: "JBL", color: "lime", emoji: "🤓" },
  ],
  players: [
    {
      id: "horty",
      name: "HortyUnderscore",
      quote: "Clairement on est pas ici pour les skills.",
      teamId: "SOINC",
      twitch: "https://www.twitch.tv/hortyunderscore",
      twitter: "https://twitter.com/HortyUnderscore",
      discord: "https://discord.gg/horty",
      youtube: "http://www.youtube.com/c/Hortense_Horty",
      instagram: "https://instagram.com/hortyunderscore",
      tiktok: "https://tiktok.com/@hortyunderscore",
    },
    {
      id: "naka",
      name: "Naka",
      quote: "Solu",
      teamId: "SOINC",
      twitter: "https://twitter.com/Nakatine_",
      discord: "https://discord.gg/5U3dxMKeEE",
      youtube: "https://www.youtube.com/@Nakavideos",
      tiktok: "https://www.tiktok.com/@nakastream",
    },
    {
      id: "jday",
      name: "MisterJday",
      quote: "Salut c'est MisterJDay et je joue à Mario.",
      teamId: "WQZ",
      twitch: "https://www.twitch.tv/misterjday",
      twitter: "http://twitter.com/MisterJDay",
      youtube: "https://www.youtube.com/JDay",
      bluesky: "https://bsky.app/profile/misterjday.bsky.social",
    },
    {
      id: "angle",
      name: "AngleDroit",
      quote: "Jeu vidéo, vulgarisation juridique et parfois, les deux en même temps.",
      teamId: "WQZ",
      twitch: "https://www.twitch.tv/angledroit",
      twitter: "https://twitter.com/AngleDroit_",
      discord: "https://discord.gg/AEcqXfn",
      youtube: "https://www.youtube.com/channel/UC_KidpuCqhbvqZedgq2DPpA/",
      instagram: "https://www.instagram.com/angledroit_",
    },
    {
      id: "ponce",
      name: "Ponce",
      quote: "Nous sommes de très jolies fleurs dans un même bouquet.",
      teamId: "FCF",
      twitch: "https://twitch.tv/ponce",
      twitter: "http://twitter.com/Poncefleur",
      discord: "https://discord.com/invite/ponce",
      youtube: "https://www.youtube.com/channel/UCKKY2Jcg_P9fhfHD3ICyMxg",
      bluesky: "https://bsky.app/profile/poncefleur.bsky.social",
      instagram: "http://instagram.com/poncefleur_",
      tiktok: "https://www.tiktok.com/@poncefleur_",
    },
    {
      id: "bytell",
      name: "Bytell",
      quote: "On rigole ici, c'est fou ce qu'on peut rire",
      teamId: "FCF",
      twitch: "https://www.twitch.tv/bytell2",
      twitter: "https://twitter.com/Bytell2",
      discord: "https://discord.gg/7xXsyTb",
      youtube: "https://www.youtube.com/user/bytell2",
      instagram: "https://www.instagram.com/bytell2/",
    },
    {
      id: "guill",
      name: "TheGuill84",
      quote: "J'ai 25 ans et je joue autant à Minecraft que quand j'en avais 12, comme quoi...",
      teamId: "FCF",
      twitch: "https://www.twitch.tv/theguill84",
      twitter: "https://twitter.com/theguill84",
      discord: "https://discord.gg/guill",
      youtube: "https://www.youtube.com/user/theguill84",
      instagram: "https://www.instagram.com/guillcstl/",
      tiktok: "https://www.tiktok.com/@theguill84",
    },
    {
      id: "zerator",
      name: "ZeratoR",
      quote: "Casu à mon grand dam mais j'organise des trucs",
      teamId: "MDR",
      twitch: "https://www.twitch.tv/zerator",
      twitter: "https://twitter.com/ZeratoR",
      discord: "https://discord.gg/zerator",
      youtube: "https://youtube.com/ZeratoR",
      instagram: "https://www.instagram.com/zerator",
      tiktok: "https://www.tiktok.com/@zerator",
    },
    {
      id: "hyp",
      name: "HyP",
      quote: "Valorant Player for MandatoryGG",
      teamId: "MDR",
      twitch: "https://www.twitch.tv/hyp_tv",
      twitter: "https://x.com/HyPOfficial",
    },
    {
      id: "khalen",
      name: "Khalen",
      quote: "CHAMPION ZLAN 2021, y'a plus rien d'autre qui compte",
      teamId: "GBG",
      twitch: "https://www.twitch.tv/kha_len",
      twitter: "https://twitter.com/ElKhaLeN",
      discord: "https://discord.gg/qWEngg4",
    },
    {
      id: "aypierre",
      name: "Aypierre",
      quote: "Minecraft Champion PVP de France et d'Europe",
      teamId: "GBG",
      twitch: "https://www.twitch.tv/aypierre",
      twitter: "https://twitter.com/AypierreMc",
      youtube: "https://www.youtube.com/channel/UCA5sfitizqs1oEbB5KY4uKQ",
      instagram: "https://www.instagram.com/aypierre/",
    },
    {
      id: "baghera",
      name: "BagheraJones",
      quote: "On fait rien et c'est rigolo",
      teamId: "PP",
      twitch: "https://www.twitch.tv/bagherajones",
      twitter: "https://twitter.com/Baghera__Jones",
      youtube: "https://www.youtube.com/channel/UCJQupr7XZ2y2fnx5i1-YavQ",
      instagram: "https://www.instagram.com/bagherajones/",
      discord: "https://discord.gg/yqBmEBP",
    },
    {
      id: "antoine",
      name: "Antoine Daniel",
      quote: "Et oui je suis là",
      teamId: "PP",
      twitch: "https://www.twitch.tv/antoinedaniel",
      discord: "https://discord.gg/aVHrA7y",
      instagram: "https://www.instagram.com/mr.antoinedaniel/",
      tiktok: "https://www.tiktok.com/@mr.antoinedaniel?lang=fr",
    },
    {
      id: "croco",
      name: "CrocodyleTV",
      quote: "CrocodyleTV streams Pokémon Black/White, League of Legends and Minecraft.",
      teamId: "HEL",
      twitch: "https://www.twitch.tv/crocodyletv",
      twitter: "https://twitter.com/Crocodyle_TV",
      discord: "https://discord.gg/ticrocoentreprise",
      youtube: "https://www.youtube.com/channel/UCI4bdgU-hmz5AgGOKVq_yuQ",
      instagram: "https://www.instagram.com/ticroco_lol/",
      tiktok: "https://www.tiktok.com/@ticrocotv",
    },
    {
      id: "kenny",
      name: "KennyStream",
      quote:
        "Petit streamer indépendant qui joue principalement à des jeux compétitifs et aime s'illustrer dans différentes compétitions, mais sinon, je joue à pleins de trucs variés et j'adore vous faire découvrir de nouvelles choses ! ⚡",
      teamId: "HEL",
      twitch: "https://www.twitch.tv/kennystream",
      twitter: "http://www.twitter.com/kennystream",
      youtube: "https://www.youtube.com/kenny",
      instagram: "https://www.instagram.com/kennysurinsta/",
    },
    {
      id: "etoiles",
      name: "Etoiles",
      quote: "Nuit de la culture, minecraft, smash et multigaming entre amis !",
      teamId: "ACT",
      twitch: "https://www.twitch.tv/etoiles",
      twitter: "http://twitter.com/AREtoiles",
      discord: "https://www.discord.gg/etoiles",
      youtube: "https://www.youtube.com/@AREtoilesMC",
      instagram: "https://www.instagram.com/etoilaisse/?hl=fr",
    },
    {
      id: "julgane",
      name: "Julgane",
      quote: "Je sais pas jouer aux Jeux-Vidéo normalement...",
      teamId: "TT",
      twitch: "https://www.twitch.tv/julgane",
      twitter: "https://x.com/Julgane",
      discord: "https://discord.com/invite/b2HzbF2",
      youtube: "https://www.youtube.com/@Julgane",
      instagram: "https://www.instagram.com/julgane_/",
    },
    {
      id: "gius",
      name: "Gius",
      quote: "Ici, on vient pour se divertir, progresser et partager.",
      teamId: "MDR",
      twitch: "https://www.twitch.tv/gius",
      twitter: "https://x.com/GiusTV",
      discord: "https://discord.com/invite/giustv",
      youtube: "https://www.youtube.com/@GiusYouTube",
      instagram: "https://www.instagram.com/giustv/",
    },
    {
      id: "gaspow",
      name: "Gaspow",
      quote: "French Rocket League Player",
      teamId: "PDG",
      twitch: "https://www.twitch.tv/gaspowrl",
      twitter: "https://twitter.com/GaspowRL",
      discord: "https://discord.gg/GUyUq7hQDb",
      youtube: "https://www.youtube.com/channel/UCPgqNtig_GJU2z83lGR276w",
      instagram: "https://www.instagram.com/gaspowrl/",
      tiktok: "https://www.tiktok.com/@gaspowrl",
    },
    {
      id: "dhalen",
      name: "Dhalen",
      quote:
        "C'est systématiquement débile, mais c'est toujours inattendu. Et ça, c'est très important pour la santé.",
      teamId: "PDG",
      twitch: "https://www.twitch.tv/dhalen",
      twitter: "https://twitter.com/DhalenTwitch",
      youtube: "https://www.youtube.com/@dhalen2",
      discord: "https://discord.gg/YsnbHpK",
    },
    {
      id: "poachimpa",
      name: "Poachimpa",
      quote:
        "Joueuse Rocket League mais pas que. De 9h30 à 13h on parle de tout et de rien, le but c'est de passer une bonne matinée ! Je joue parfois à d'autres trucs, valorant ou simulateurs. Je caste aussi notamment chez @RocketBaguette.",
      teamId: "PDG",
      twitch: "https://www.twitch.tv/poachimpa",
      twitter: "https://twitter.com/Poachimpa",
      youtube: "https://www.youtube.com/@poachimpa_",
      discord: "https://discord.gg/n97CZVZCFF",
      tiktok: "https://www.tiktok.com/@poachimpa",
    },
    {
      id: "lutti",
      name: "Lutti",
      quote:
        "Animateur, Commentateur, Improvisateur. C'est pas moi qui parle vite c'est votre cerveau qui est trop lent !",
      teamId: "MDR",
      twitch: "https://www.twitch.tv/lutti",
      twitter: "https://twitter.com/LuttiLutti_",
      youtube: "https://www.youtube.com/user/GamersOriginHS",
      tiktok: "https://www.tiktok.com/@luttilutti?lang=fr",
    },
    {
      id: "jimmyboy",
      name: "JimmyBoy",
      quote: "",
      teamId: "STNK",
    },
    {
      id: "laink",
      name: "Laink",
      quote: "weeee",
      teamId: "FCF",
      twitch: "https://www.twitch.tv/laink",
      twitter: "https://twitter.com/laink",
      youtube: "https://www.youtube.com/c/wankilfr",
      instagram: "https://www.instagram.com/lainkk/",
      tiktok: "https://www.tiktok.com/@lainkk",
    },
    {
      id: "bichard",
      name: "Bichard",
      quote:
        "Je suis juste là pour essayer de vous faire rire ! Animation | Projet d'envergure | Sociable | Motivé | Sourire communicatif. Tous les éléments sont présents pour passer un bon moment.",
      teamId: "JBL",
      twitch: "https://www.twitch.tv/bichard",
      twitter: "https://twitter.com/FaresBichard",
      youtube: "https://youtube.com/c/Bichard",
      instagram: "https://instagram.com/FaresBichard",
      discord: "https://discord.gg/BEehjgw",
    },
    {
      id: "gobgg",
      name: "GobGG",
      quote: "Je me lève chaque matin pour jouer devant une communauté en or : la vie de rêve",
      teamId: "P4",
      twitch: "https://www.twitch.tv/gobgg",
      instagram: "https://www.instagram.com/gob_gg",
      youtube: "https://www.youtube.com/@GoBGG_YT/videos",
      tiktok: "https://www.tiktok.com/@gobstream",
    },
  ],
  times: [
    { playerId: "horty", mapId: "map_0", editionId: "1", time: "01:08:08.061" },
    { playerId: "horty", mapId: "map_1", editionId: "2", time: "03:20:49.664" },
    { playerId: "horty", mapId: "map_2", editionId: "3", time: "02:57:12.616" },
    {
      playerId: "horty",
      mapId: "map_3",
      editionId: "4",
      time: "01:43:17.409",
      replay: "https://www.twitch.tv/videos/2342401421",
    },
    { playerId: "naka", mapId: "map_0", editionId: "1", time: "01:07:56.867" },
    { playerId: "naka", mapId: "map_1", editionId: "2", time: "03:20:33.624" },
    { playerId: "naka", mapId: "map_2", editionId: "3", time: "02:57:46.783" },
    { playerId: "naka", mapId: "map_3", editionId: "4", time: "01:43:33.690" },
    { playerId: "zerator", mapId: "map_3", editionId: "4", time: "58:54.761" },
    { playerId: "zerator", mapId: "map_4", editionId: "5", time: "01:42:21.810" },
    { playerId: "zerator", mapId: "map_5", editionId: "5", time: "01:02:50.238" },
    { playerId: "hyp", mapId: "map_3", editionId: "4", time: "58:43.119" },
    { playerId: "hyp", mapId: "map_4", editionId: "5", time: "01:42:46.353" },
    { playerId: "hyp", mapId: "map_5", editionId: "5", time: "01:03:10.958" },
    {
      playerId: "ponce",
      mapId: "map_0",
      editionId: "1",
      time: "58:25.548",
      replay: "https://www.youtube.com/watch?v=HG83jkkOfMc",
    },
    {
      playerId: "ponce",
      mapId: "map_1",
      editionId: "2",
      time: "02:37:10.103",
      replay: "https://www.youtube.com/watch?v=Wx0SzPbq0Ow",
    },
    {
      playerId: "ponce",
      mapId: "map_2",
      editionId: "3",
      time: "02:31:21.467",
      replay: "https://www.youtube.com/watch?v=OLtWKcLYDUc",
    },
    {
      playerId: "ponce",
      mapId: "map_3",
      editionId: "4",
      time: "01:10:31.130",
      replay: "https://www.youtube.com/watch?v=SOsYbZEHQSk",
    },
    {
      playerId: "ponce",
      mapId: "map_4",
      editionId: "5",
      time: "02:24:38.928",
      replay: "https://www.youtube.com/watch?v=gAjUXozQkTk",
    },
    {
      playerId: "ponce",
      mapId: "map_5",
      editionId: "5",
      time: "01:03:00.890",
      replay: "https://www.youtube.com/watch?v=gAjUXozQkTk&t=11311",
    },
    { playerId: "bytell", mapId: "map_0", editionId: "1", time: "01:03:47.796" },
    { playerId: "bytell", mapId: "map_1", editionId: "2", time: "03:13:51.812" },
    { playerId: "bytell", mapId: "map_2", editionId: "3", time: "02:31:34.346" },
    {
      playerId: "guill",
      mapId: "map_3",
      editionId: "4",
      time: "01:10:33.688",
      replay: "https://www.youtube.com/watch?v=jubyQF0dp68",
    },
    {
      playerId: "guill",
      mapId: "map_4",
      editionId: "5",
      time: "02:26:07.795",
      replay: "https://www.youtube.com/watch?v=ASbIG2wTNp8",
    },
    {
      playerId: "guill",
      mapId: "map_5",
      editionId: "5",
      time: "01:03:56.389",
      replay: "https://www.youtube.com/watch?v=ASbIG2wTNp8&t=10763",
    },
    { playerId: "khalen", mapId: "map_4", editionId: "5", time: "01:47:51.355" },
    { playerId: "khalen", mapId: "map_5", editionId: "5", time: "01:03:41.489" },
    { playerId: "aypierre", mapId: "map_4", editionId: "5", time: "01:47:59.588" },
    { playerId: "aypierre", mapId: "map_5", editionId: "5", time: "01:05:09.351" },
    {
      playerId: "jday",
      mapId: "map_0",
      editionId: "1",
      time: "01:18:18.838",
      replay: "https://www.youtube.com/watch?v=brv1mTMWxuI",
    },
    {
      playerId: "jday",
      mapId: "map_1",
      editionId: "2",
      time: "03:19:15.983",
      replay: "https://www.youtube.com/watch?v=qhaY47lewKU",
    },
    {
      playerId: "jday",
      mapId: "map_2",
      editionId: "3",
      time: "02:41:39.084",
      replay: "https://www.youtube.com/watch?v=O-aw6YA9q98",
    },
    {
      playerId: "jday",
      mapId: "map_3",
      editionId: "4",
      time: "01:34:15.639",
      replay: "https://www.youtube.com/watch?v=GwU_2IT33DU",
    },
    {
      playerId: "angle",
      mapId: "map_0",
      editionId: "1",
      time: "01:18:17.421",
      replay: "https://www.youtube.com/watch?v=u-I5ASNRzlw",
    },
    {
      playerId: "angle",
      mapId: "map_1",
      editionId: "2",
      time: "03:20:23.988",
      replay: "https://www.youtube.com/watch?v=eiZNEyBZxvY",
    },
    {
      playerId: "angle",
      mapId: "map_2",
      editionId: "3",
      time: "02:42:13.305",
      replay: "https://www.youtube.com/watch?v=3iGoPxGWA3Y",
    },
    {
      playerId: "angle",
      mapId: "map_3",
      editionId: "4",
      time: "01:40:20.934",
      replay: "https://www.youtube.com/watch?v=gsVLUj9I1LE",
    },
    {
      playerId: "jday",
      mapId: "map_6",
      editionId: "6",
      time: "55:21.784",
      replay: "https://www.youtube.com/watch?v=WSLBgUooXVw",
    },
    { playerId: "angle", mapId: "map_6", editionId: "6", time: "55:30.185" },
    {
      playerId: "antoine",
      mapId: "map_6",
      editionId: "6",
      time: "46:02.764",
      replay: "https://www.youtube.com/watch?v=8j8QhMGEZw8",
    },
    {
      playerId: "baghera",
      mapId: "map_6",
      editionId: "6",
      time: "45:56.729",
      replay: "https://www.youtube.com/watch?v=-J3yxiPxwk4",
    },
    {
      playerId: "naka",
      mapId: "map_6",
      editionId: "6",
      teamId: "DOMO",
      time: "52:50.439",
      replay: "https://www.youtube.com/watch?v=A4OSOJJx374",
    },
    {
      playerId: "bytell",
      mapId: "map_6",
      editionId: "6",
      teamId: "DOMO",
      time: "53:56.938",
    },
    {
      playerId: "jday",
      mapId: "map_5",
      editionId: "6",
      time: "2:15:14.545",
      replay: "https://www.youtube.com/watch?v=WSLBgUooXVw&t=6274",
    },
    {
      playerId: "antoine",
      mapId: "map_5",
      editionId: "6",
      time: "2:39:35.297",
      replay: "https://www.youtube.com/watch?v=vGIaFMKANwk",
    },
    {
      playerId: "baghera",
      mapId: "map_5",
      editionId: "6",
      time: "2:36:45.584",
      replay: "https://www.youtube.com/watch?v=-J3yxiPxwk4&t=4910",
    },
    {
      playerId: "naka",
      mapId: "map_5",
      editionId: "6",
      teamId: "DOMO",
      time: "2:43:39.194",
      replay: "https://www.youtube.com/watch?v=m6FA3_-BVBA",
    },
    {
      playerId: "bytell",
      mapId: "map_5",
      editionId: "6",
      teamId: "DOMO",
      time: "2:48:32.968",
    },
    {
      playerId: "zerator",
      mapId: "map_7",
      editionId: "7",
      time: "40:29.554",
      replay: "https://www.youtube.com/watch?v=8YMFGkjYuzE&t=841",
    },
    { playerId: "hyp", mapId: "map_7", editionId: "7", time: "41:00.668" },
    {
      playerId: "khalen",
      mapId: "map_7",
      editionId: "7",
      teamId: "SPF",
      time: "40:26.102",
    },
    {
      playerId: "guill",
      mapId: "map_7",
      editionId: "7",
      teamId: "SPF",
      time: "40:28.342",
    },
    {
      playerId: "horty",
      mapId: "map_7",
      editionId: "7",
      teamId: "ACT",
      time: "02:10:19.058",
      replay: "https://www.youtube.com/watch?v=sbdjYAIwYBs",
    },
    {
      playerId: "etoiles",
      mapId: "map_7",
      editionId: "7",
      time: "02:10:17.683",
      replay: "https://www.youtube.com/watch?v=kVh4WIBfvgw",
    },
    {
      playerId: "croco",
      mapId: "map_7",
      editionId: "7",
      time: "46:47.488",
      replay: "https://www.youtube.com/watch?v=cJaKpUmzGF8",
    },
    { playerId: "kenny", mapId: "map_7", editionId: "7", time: "46:36.274" },
    { playerId: "zerator", mapId: "map_6", editionId: "7", time: "22:02.206" },
    {
      playerId: "khalen",
      mapId: "map_6",
      editionId: "7",
      teamId: "MDR",
      time: "22:02.895",
    },
    {
      playerId: "etoiles",
      mapId: "map_6",
      editionId: "7",
      teamId: "HEL",
      time: "31:07.567",
      replay: "https://www.youtube.com/watch?v=03my22hT3KQ",
    },
    {
      playerId: "croco",
      mapId: "map_6",
      editionId: "7",
      time: "30:48.836",
      replay: "https://www.youtube.com/watch?v=cJaKpUmzGF8&t=10938",
    },
    { playerId: "kenny", mapId: "map_6", editionId: "7", time: "30:47.400" },

    // Edition 8
    { playerId: "ponce", mapId: "map_8", editionId: "8", time: "35:47.488" },
    { playerId: "kenny", mapId: "map_8", editionId: "8", teamId: "FCF", time: "35:47.488" },
    { playerId: "croco", mapId: "map_8", editionId: "8", teamId: "FCF", time: "35:47.488" },

    { playerId: "khalen", mapId: "map_8", editionId: "8", teamId: "TT", time: "29:48.484" },
    { playerId: "julgane", mapId: "map_8", editionId: "8", time: "29:48.484" },
    { playerId: "etoiles", mapId: "map_8", editionId: "8", teamId: "TT", time: "29:48.484" },
    { playerId: "hyp", mapId: "map_8", editionId: "8", time: "27:57.243" },
    { playerId: "zerator", mapId: "map_8", editionId: "8", time: "27:57.243" },
    { playerId: "gius", mapId: "map_8", editionId: "8", time: "27:57.243" },

    { playerId: "horty", mapId: "map_8", editionId: "8", time: "1:25:30.977" },
    { playerId: "naka", mapId: "map_8", editionId: "8", time: "1:25:30.977" },

    { playerId: "jday", mapId: "map_8", editionId: "8", time: "1:00:22.216" },
    { playerId: "angle", mapId: "map_8", editionId: "8", time: "1:00:22.216" },
    { playerId: "antoine", mapId: "map_8", editionId: "8", time: "1:00:22.216" },

    { playerId: "gaspow", mapId: "map_8", editionId: "8", time: "46:50.719" },
    { playerId: "dhalen", mapId: "map_8", editionId: "8", time: "46:50.719" },
    { playerId: "poachimpa", mapId: "map_8", editionId: "8", time: "46:50.719" },

    // Edition 9
    { playerId: "guill", mapId: "map_9", editionId: "9", teamId: "GG", time: "47:05.600" },
    { playerId: "gaspow", mapId: "map_9", editionId: "9", teamId: "GG", time: "47:05.600" },
    { playerId: "lutti", mapId: "map_9", editionId: "9", time: "56:50.575" },
    { playerId: "hyp", mapId: "map_9", editionId: "9", time: "56:50.575" },
    { playerId: "kenny", mapId: "map_9", editionId: "9", teamId: "K2", time: "30:58.164" },
    { playerId: "khalen", mapId: "map_9", editionId: "9", teamId: "K2", time: "30:58.164" },

    // Edition 10
    { playerId: "zerator", mapId: "map_10", editionId: "10", time: "1:11:38.738" },
    { playerId: "hyp", mapId: "map_10", editionId: "10", time: "1:12:11.554" },
    { playerId: "kenny", mapId: "map_10", editionId: "10", teamId: "PAC", time: "1:23:41.803" },
    { playerId: "etoiles", mapId: "map_10", editionId: "10", teamId: "PAC", time: "1:22:57.134" },
    { playerId: "khalen", mapId: "map_10", editionId: "10", teamId: "CL", time: "49:41.003" },
    { playerId: "gaspow", mapId: "map_10", editionId: "10", teamId: "CL", time: "49:33.393" },

    // Edition 12
    { playerId: "ponce", mapId: "map_11", editionId: "12", teamId: "EDW", time: "39:01.121" },
    { playerId: "jday", mapId: "map_11", editionId: "12", teamId: "EDW", time: "39:01.121" },
    { playerId: "aypierre", mapId: "map_11", editionId: "12", teamId: "STNK", time: "29:44.971" },
    { playerId: "jimmyboy", mapId: "map_11", editionId: "12", time: "29:44.971" },
    { playerId: "gaspow", mapId: "map_11", editionId: "12", teamId: "CL", time: "48:04.986" },
    { playerId: "poachimpa", mapId: "map_11", editionId: "12", teamId: "CL", time: "48:04.986" },

    // Edition 13
    { playerId: "hyp", mapId: "map_12", editionId: "13", time: "1:36:00.975" },
    { playerId: "zerator", mapId: "map_12", editionId: "13", time: "1:36:56.547" },
    { playerId: "gius", mapId: "map_12", editionId: "13", time: "1:36:56.547" },
    { playerId: "jday", mapId: "map_12", editionId: "13", time: "2:55:59.269" },
    { playerId: "julgane", mapId: "map_12", editionId: "13", teamId: "WQZ", time: "2:55:59.269" },
    { playerId: "angle", mapId: "map_12", editionId: "13", time: "2:55:59.269" },
    { playerId: "kenny", mapId: "map_12", editionId: "13", teamId: "FCF", time: "1:29:25.000" },
    { playerId: "laink", mapId: "map_12", editionId: "13", time: "1:30:37.128" },
    { playerId: "ponce", mapId: "map_12", editionId: "13", time: "1:30:13.300" },
    { playerId: "jimmyboy", mapId: "map_12", editionId: "13", teamId: "JBL", time: "1:27:59.527" },
    { playerId: "bichard", mapId: "map_12", editionId: "13", time: "1:28:03.237" },
    { playerId: "lutti", mapId: "map_12", editionId: "13", teamId: "JBL", time: "1:28:52.565" },
    { playerId: "gaspow", mapId: "map_12", editionId: "13", teamId: "P4", time: "2:03:06.756" },
    { playerId: "gobgg", mapId: "map_12", editionId: "13", time: "2:03:06.756" },
    { playerId: "khalen", mapId: "map_12", editionId: "13", teamId: "P4", time: "2:03:06.756" },
    { playerId: "dhalen", mapId: "map_12", editionId: "13", teamId: "P4", time: "2:03:06.756" },

    // Edition 14
    { playerId: "zerator", mapId: "map_13", editionId: "14", time: "54:26.314" },
    { playerId: "hyp", mapId: "map_13", editionId: "14", time: "54:26.314" },
    { playerId: "khalen", mapId: "map_13", editionId: "14", teamId: "CL", time: "36:24.474" },
    { playerId: "gaspow", mapId: "map_13", editionId: "14", teamId: "CL", time: "36:24.474" },
    { playerId: "jimmyboy", mapId: "map_13", editionId: "14", teamId: "CUBE", time: "53:45.414" },
    { playerId: "guill", mapId: "map_13", editionId: "14", teamId: "CUBE", time: "53:45.414" },
  ],
  maps: [
    {
      id: "map_0",
      name: "Treasure Islands",
      author: "ziyx_",
      exchangeId: "153644",
      authorTime: "03:52.878",
      difficulty: "Facile +",
    },
    {
      id: "map_1",
      name: "Oblivion - Novice",
      author: "Qiraj",
      exchangeId: "177289",
      authorTime: "08:46.195",
      difficulty: "Difficile",
    },
    {
      id: "map_2",
      name: "Kepler-B23 - novice",
      author: "Heasto",
      exchangeId: "184838",
      authorTime: "05:09.136",
      difficulty: "Moyen +",
    },
    {
      id: "map_3",
      name: "Onyxtemple",
      author: "Onyx_be01",
      exchangeId: "214814",
      authorTime: "04:16.396",
      difficulty: "Moyen -",
    },
    {
      id: "map_4",
      name: "Pylos",
      author: "SirTalyon",
      exchangeId: "224823",
      authorTime: "05:51.025",
      difficulty: "Difficile",
    },
    {
      id: "map_5",
      name: "Horizon's Edge - Sector A",
      author: "Qiraj",
      exchangeId: "204909",
      authorTime: "04:36.305",
      difficulty: "Difficile",
    },
    {
      id: "map_6",
      name: "Cirrus - Easy",
      author: "NeoriionTM",
      exchangeId: "227562",
      authorTime: "04:31.526",
      difficulty: "Facile",
    },
    {
      id: "map_7",
      name: "Animus Project",
      author: "Raikuz",
      exchangeId: "230081",
      authorTime: "05:25.971",
      difficulty: "Moyen",
    },
    {
      id: "map_8",
      name: "Hunted House",
      author: "KannTM",
      exchangeId: "253624",
      authorTime: "05:00.245",
      difficulty: "Débutant",
    },
    {
      id: "map_9",
      name: "Infectious",
      author: "Onyx_be01",
      exchangeId: "270746",
      authorTime: "04:28.198",
      difficulty: "Intermédiaire",
    },
    {
      id: "map_10",
      name: "Darakûn",
      author: "Qiraj",
      exchangeId: "270885",
      authorTime: "08:44.658",
      difficulty: "Intermédiaire",
    },
    {
      id: "map_11",
      name: "Earth Wound",
      author: "Wazix",
      exchangeId: "282739",
      authorTime: "04:22.931",
      difficulty: "Intermédiaire",
    },
    {
      id: "map_12",
      name: "Frostguard Citadel",
      author: "Roquete.wp",
      exchangeId: "273721",
      authorTime: "08:58.147",
      difficulty: "Intermédiaire",
    },
    {
      id: "map_13",
      name: "Silent Echo",
      author: "Qiraj",
      exchangeId: "289593",
      authorTime: "04:07.289",
      difficulty: "Intermédiaire",
    },
  ],
  editions: [
    {
      id: "1",
      date: "2024/02/07",
      mapsIds: ["map_0"],
      recapVideos: ["https://www.youtube.com/watch?v=SiOqw3fzmPY"],
      winnerTeamId: "FCF",
      announcementTweet:
        "https://x.com/Wingo_Bear/status/1754804610370334945?t=FErD72cUa-Yt342x6jatVw&s=19",
      announcementTrailer: false,
      announcementPicture: true,
    },
    {
      id: "2",
      date: "2024/06/19",
      mapsIds: ["map_1"],
      recapVideos: ["https://www.youtube.com/watch?v=52L6yayRVSs"],
      winnerTeamId: "FCF",
      announcementTweet:
        "https://x.com/Wingo_Bear/status/1803485608263778481?t=-K0JvJKBuHnHFBNr2QNODg&s=19",
      announcementTrailer: true,
      announcementPicture: true,
    },
    {
      id: "3",
      date: "2024/07/31",
      mapsIds: ["map_2"],
      recapVideos: ["https://www.youtube.com/watch?v=h4Xcngm3JEI"],
      winnerTeamId: "FCF",
      announcementTweet:
        "https://x.com/Wingo_Bear/status/1817524085435351164?t=gcdubGnYGgXCqSxhcgv0eA&s=19",
      announcementTrailer: true,
      announcementPicture: true,
    },
    {
      id: "4",
      date: "2024/12/18",
      mapsIds: ["map_3"],
      recapVideos: ["https://www.youtube.com/watch?v=Bd1aoUVZ25c"],
      winnerTeamId: "MDR",
      announcementTweet: "https://x.com/Wingo_Bear/status/1868639936922210743",
      announcementTrailer: true,
      announcementPicture: true,
    },
    {
      id: "5",
      date: "2025/02/04",
      mapsIds: ["map_4", "map_5"],
      recapVideos: [
        "https://www.youtube.com/watch?v=4VmFLBhD8sk",
        "https://www.youtube.com/watch?v=-yH21KAc2VQ",
      ],
      winnerTeamId: "MDR",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: true,
    },
    {
      id: "6",
      date: "2025/02/19",
      mapsIds: ["map_6", "map_5"],
      recapVideos: [
        "https://www.youtube.com/watch?v=Q3kU9avToYg",
        "https://www.youtube.com/watch?v=W3BmSQUSyvM",
      ],
      winnerTeamId: "PP",
      announcementTweet: "https://x.com/Wingo_Bear/status/1891097339911192967",
      announcementTrailer: false,
      announcementPicture: true,
    },
    {
      id: "7",
      date: "2025/03/13",
      mapsIds: ["map_7", "map_6"],
      recapVideos: ["https://www.youtube.com/watch?v=8KEnKlhqgK0"],
      winnerTeamId: "SPF",
      announcementTweet: "https://x.com/Wingo_Bear/status/1898714089590763937",
      announcementTrailer: true,
      announcementPicture: true,
    },
    {
      id: "8",
      date: "2025/07/02",
      mapsIds: ["map_8"],
      recapVideos: [],
      winnerTeamId: "MDR",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
    {
      id: "9",
      date: "2025/09/01",
      mapsIds: ["map_9"],
      recapVideos: [],
      winnerTeamId: "K2",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
    {
      id: "10",
      date: "2025/10/28",
      mapsIds: ["map_10"],
      recapVideos: [],
      winnerTeamId: "CL",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
    {
      id: "12",
      date: "2025/12/18",
      mapsIds: ["map_11"],
      recapVideos: [],
      winnerTeamId: "STNK",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
    {
      id: "13",
      date: "2026/01/22",
      mapsIds: ["map_12"],
      recapVideos: [],
      winnerTeamId: "JBL",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
    {
      id: "14",
      date: "2026/02/26",
      mapsIds: ["map_13"],
      recapVideos: [],
      winnerTeamId: "CL",
      announcementTweet: "",
      announcementTrailer: false,
      announcementPicture: false,
    },
  ],
};
