services:
  website-v6-php-terminal:
    image: php:7.4.3-apache
    container_name: website-v6-php-terminal
    restart: unless-stopped
    # Only expose port if direct access is needed
    # ports:
    #   - 10006:80
    volumes:
      - ./:/var/www/html
    networks:
      - my-website-network
